### PR TITLE
MAISTRA-791 Removed grafana user and group creation from the spec file

### PR DESCRIPTION
**Pull request by dmitri-d**

### CODE REVIEW

**Review by jwendell — APPROVED** [review]
PR itself LGTM, although it would be good to explain in the commit message why this change is necessary. I, for example, have no idea why grafana needed to run as a normal user and now it runs as root.

**Comment by dmitri-d** [comment]
* updated commit message to include explanation re: removal of grafana user.

**Comment by jwendell** [comment]
@dmitri-d  thanks

**Review by brian-avery — APPROVED** [review]

**Review by knrc — APPROVED** [review]

**Pull request merged**
