### PR TITLE
Fixed fetch.sh

### PR DESCRIPTION
**Pull request by brian-avery**
With changes to WORKSPACE (https://github.com/Maistra/proxy/commit/f777dd13e28edc4ff394e98cd82c82ca4a2bcc71), the comment for HTTP_ARCHIVE has been removed in favor of a build argument. This PR updates the test and fetch scripts to use this new arg.

### CODE REVIEW

**Review by dmitri-d — COMMENTED** [review]
I think you also need to override_repository here: https://github.com/Maistra/rpms/blob/58a3df902fc7a9fc899cc05082d1063fe7171ac9/istio-proxy/fetch.sh#L188

**Comment by brian-avery** [comment]
> I think you also need to override_repository here:
> 
> https://github.com/Maistra/rpms/blob/58a3df902fc7a9fc899cc05082d1063fe7171ac9/istio-proxy/fetch.sh#L188

The patch to make this use local was after this. So I don't think this needs the override_repository

**Comment by dmitri-d** [comment]
> The patch to make this use local was after this. So I don't think this needs the override_repository

We'd be pulling a (potentially) different set of envoy dependencies during the first fetch. This may or may not be an issue right now, but it would've saved me a few hours yesterday trying to figure out why my dependency wasn't being downloaded.

**Review by jwendell — APPROVED** [review]

**Comment by jwendell** [comment]
Manually merging

**Review by knrc — COMMENTED** [review]
For what it's worth this PR seems to be fine, let's make sure these get reviewed next time

**Pull request merged**
